version: '3.9'

services:
  pg:
    image: postgres:16.3-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${DOCKER__PG_USER}
      POSTGRES_PASSWORD: ${DOCKER__PG_PASSWORD}
      POSTGRES_DB: ${DOCKER__PG_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${DOCKER__PG_USER} -d ${DOCKER__PG_DB}
      interval: 5s
      timeout: 3s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER__IMAGE}
    restart: always
    depends_on:
      pg:
        condition: service_healthy
    volumes:
      - ./src/:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  postgres_data: